apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-apache-deployment
  labels:
    app: ubuntu-apache
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ubuntu-apache
  template:
    metadata:
      labels:
        app: ubuntu-apache
    spec:
      containers:
      - name: ubuntu-apache-container
        image: manasitdk/ubuntu_images:ubuntu-apache-1.0.2
        ports:
        - containerPort: 80  # Assuming the web server is listening on port 80
---
apiVersion: v1
kind: Service
metadata:
  name: ubuntu-apache-service
  labels:
    app: ubuntu-apache
spec:
  type: NodePort
  selector:
    app: ubuntu-apache
  ports:
    - protocol: TCP
      port: 80           # The port the service will use inside the cluster
      targetPort: 80      # The port the container is exposing
      nodePort: 32900     # NodePort for external access
