apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-apache-deployment
  labels:
    app: ubuntu-apache               # Add a label for better identification
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ubuntu-apache
  template:
    metadata:
      labels:
        app: ubuntu-apache
    spec:
      containers:
      - name: ubuntu-apache
        image: manasitdk/ubuntu_images:ubuntu-apache-1.0.3
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ubuntu-apache-service
spec:
  type: NodePort
  selector:
    app: ubuntu-apache
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 32900    # NodePort range: 30000-32767
